// @File auto-generated by generate_header.lua, do not modify
// @Date 06/13/13
#ifndef DUNE_COMMON_TUPLES_MODIFIERS_INCLUDE_HH
#define DUNE_COMMON_TUPLES_MODIFIERS_INCLUDE_HH

#include <dune/common/tuples/tuples.hh>

namespace Dune
{

  // tuple_push_back
  // ---------------

  template< class T1 >
  inline Dune::tuple< T1 > tuple_push_back ( const Dune::tuple<> &t, T1 t1 )
  {
    return Dune::tuple< T1 >( t1 );
  }

  template< class T2, class T1 >
  inline Dune::tuple< T1, T2 > tuple_push_back ( const Dune::tuple< T1 > &t, T2 t2 )
  {
    return Dune::tuple< T1, T2 >( get< 0 >( t ), t2 );
  }

  template< class T3, class T1, class T2 >
  inline Dune::tuple< T1, T2, T3 > tuple_push_back ( const Dune::tuple< T1, T2 > &t, T3 t3 )
  {
    return Dune::tuple< T1, T2, T3 >( get< 0 >( t ), get< 1 >( t ), t3 );
  }

  template< class T4, class T1, class T2, class T3 >
  inline Dune::tuple< T1, T2, T3, T4 > tuple_push_back ( const Dune::tuple< T1, T2, T3 > &t, T4 t4 )
  {
    return Dune::tuple< T1, T2, T3, T4 >( get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), t4 );
  }

  template< class T5, class T1, class T2, class T3, class T4 >
  inline Dune::tuple< T1, T2, T3, T4, T5 > tuple_push_back ( const Dune::tuple< T1, T2, T3, T4 > &t, T5 t5 )
  {
    return Dune::tuple< T1, T2, T3, T4, T5 >( get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), t5 );
  }

  template< class T6, class T1, class T2, class T3, class T4, class T5 >
  inline Dune::tuple< T1, T2, T3, T4, T5, T6 > tuple_push_back ( const Dune::tuple< T1, T2, T3, T4, T5 > &t, T6 t6 )
  {
    return Dune::tuple< T1, T2, T3, T4, T5, T6 >( get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ), t6 );
  }

  template< class T7, class T1, class T2, class T3, class T4, class T5, class T6 >
  inline Dune::tuple< T1, T2, T3, T4, T5, T6, T7 > tuple_push_back ( const Dune::tuple< T1, T2, T3, T4, T5, T6 > &t, T7 t7 )
  {
    return Dune::tuple< T1, T2, T3, T4, T5, T6, T7 >( get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ), get< 5 >( t ), t7 );
  }

  template< class T8, class T1, class T2, class T3, class T4, class T5, class T6, class T7 >
  inline Dune::tuple< T1, T2, T3, T4, T5, T6, T7, T8 > tuple_push_back ( const Dune::tuple< T1, T2, T3, T4, T5, T6, T7 > &t, T8 t8 )
  {
    return Dune::tuple< T1, T2, T3, T4, T5, T6, T7, T8 >( get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ), get< 5 >( t ), get< 6 >( t ), t8 );
  }



  // tuple_push_front
  // ----------------

  template< class T1 >
  inline Dune::tuple< T1 > tuple_push_front ( const Dune::tuple<> &t, T1 t1 )
  {
    return Dune::tuple< T1 >( t1 );
  }

  template< class T1, class T2 >
  inline Dune::tuple< T1, T2 > tuple_push_front ( const Dune::tuple< T2 > &t, T1 t1 )
  {
    return Dune::tuple< T1, T2 >( t1, get< 0 >( t ) );
  }

  template< class T1, class T2, class T3 >
  inline Dune::tuple< T1, T2, T3 > tuple_push_front ( const Dune::tuple< T2, T3 > &t, T1 t1 )
  {
    return Dune::tuple< T1, T2, T3 >( t1, get< 0 >( t ), get< 1 >( t ) );
  }

  template< class T1, class T2, class T3, class T4 >
  inline Dune::tuple< T1, T2, T3, T4 > tuple_push_front ( const Dune::tuple< T2, T3, T4 > &t, T1 t1 )
  {
    return Dune::tuple< T1, T2, T3, T4 >( t1, get< 0 >( t ), get< 1 >( t ), get< 2 >( t ) );
  }

  template< class T1, class T2, class T3, class T4, class T5 >
  inline Dune::tuple< T1, T2, T3, T4, T5 > tuple_push_front ( const Dune::tuple< T2, T3, T4, T5 > &t, T1 t1 )
  {
    return Dune::tuple< T1, T2, T3, T4, T5 >( t1, get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), get< 3 >( t ) );
  }

  template< class T1, class T2, class T3, class T4, class T5, class T6 >
  inline Dune::tuple< T1, T2, T3, T4, T5, T6 > tuple_push_front ( const Dune::tuple< T2, T3, T4, T5, T6 > &t, T1 t1 )
  {
    return Dune::tuple< T1, T2, T3, T4, T5, T6 >( t1, get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ) );
  }

  template< class T1, class T2, class T3, class T4, class T5, class T6, class T7 >
  inline Dune::tuple< T1, T2, T3, T4, T5, T6, T7 > tuple_push_front ( const Dune::tuple< T2, T3, T4, T5, T6, T7 > &t, T1 t1 )
  {
    return Dune::tuple< T1, T2, T3, T4, T5, T6, T7 >( t1, get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ), get< 5 >( t ) );
  }

  template< class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8 >
  inline Dune::tuple< T1, T2, T3, T4, T5, T6, T7, T8 > tuple_push_front ( const Dune::tuple< T2, T3, T4, T5, T6, T7, T8 > &t, T1 t1 )
  {
    return Dune::tuple< T1, T2, T3, T4, T5, T6, T7, T8 >( t1, get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ), get< 5 >( t ), get< 6 >( t ) );
  }



  // tuple_pop_back
  // --------------

  template< class T1 >
  inline Dune::tuple<> tuple_pop_back ( const Dune::tuple< T1 > &t )
  {
    return Dune::tuple<>();
  }

  template< class T1, class T2 >
  inline Dune::tuple< T1 > tuple_pop_back ( const Dune::tuple< T1, T2 > &t )
  {
    return Dune::tuple< T1 >( get< 0 >( t ) );
  }

  template< class T1, class T2, class T3 >
  inline Dune::tuple< T1, T2 > tuple_pop_back ( const Dune::tuple< T1, T2, T3 > &t )
  {
    return Dune::tuple< T1, T2 >( get< 0 >( t ), get< 1 >( t ) );
  }

  template< class T1, class T2, class T3, class T4 >
  inline Dune::tuple< T1, T2, T3 > tuple_pop_back ( const Dune::tuple< T1, T2, T3, T4 > &t )
  {
    return Dune::tuple< T1, T2, T3 >( get< 0 >( t ), get< 1 >( t ), get< 2 >( t ) );
  }

  template< class T1, class T2, class T3, class T4, class T5 >
  inline Dune::tuple< T1, T2, T3, T4 > tuple_pop_back ( const Dune::tuple< T1, T2, T3, T4, T5 > &t )
  {
    return Dune::tuple< T1, T2, T3, T4 >( get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), get< 3 >( t ) );
  }

  template< class T1, class T2, class T3, class T4, class T5, class T6 >
  inline Dune::tuple< T1, T2, T3, T4, T5 > tuple_pop_back ( const Dune::tuple< T1, T2, T3, T4, T5, T6 > &t )
  {
    return Dune::tuple< T1, T2, T3, T4, T5 >( get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ) );
  }

  template< class T1, class T2, class T3, class T4, class T5, class T6, class T7 >
  inline Dune::tuple< T1, T2, T3, T4, T5, T6 > tuple_pop_back ( const Dune::tuple< T1, T2, T3, T4, T5, T6, T7 > &t )
  {
    return Dune::tuple< T1, T2, T3, T4, T5, T6 >( get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ), get< 5 >( t ) );
  }

  template< class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8 >
  inline Dune::tuple< T1, T2, T3, T4, T5, T6, T7 > tuple_pop_back ( const Dune::tuple< T1, T2, T3, T4, T5, T6, T7, T8 > &t )
  {
    return Dune::tuple< T1, T2, T3, T4, T5, T6, T7 >( get< 0 >( t ), get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ), get< 5 >( t ), get< 6 >( t ) );
  }



  // tuple_pop_front
  // ---------------

  template< class T1 >
  inline Dune::tuple<> tuple_pop_front ( const Dune::tuple< T1 > &t )
  {
    return Dune::tuple<>();
  }

  template< class T1, class T2 >
  inline Dune::tuple< T2 > tuple_pop_front ( const Dune::tuple< T1, T2 > &t )
  {
    return Dune::tuple< T2 >( get< 1 >( t ) );
  }

  template< class T1, class T2, class T3 >
  inline Dune::tuple< T2, T3 > tuple_pop_front ( const Dune::tuple< T1, T2, T3 > &t )
  {
    return Dune::tuple< T2, T3 >( get< 1 >( t ), get< 2 >( t ) );
  }

  template< class T1, class T2, class T3, class T4 >
  inline Dune::tuple< T2, T3, T4 > tuple_pop_front ( const Dune::tuple< T1, T2, T3, T4 > &t )
  {
    return Dune::tuple< T2, T3, T4 >( get< 1 >( t ), get< 2 >( t ), get< 3 >( t ) );
  }

  template< class T1, class T2, class T3, class T4, class T5 >
  inline Dune::tuple< T2, T3, T4, T5 > tuple_pop_front ( const Dune::tuple< T1, T2, T3, T4, T5 > &t )
  {
    return Dune::tuple< T2, T3, T4, T5 >( get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ) );
  }

  template< class T1, class T2, class T3, class T4, class T5, class T6 >
  inline Dune::tuple< T2, T3, T4, T5, T6 > tuple_pop_front ( const Dune::tuple< T1, T2, T3, T4, T5, T6 > &t )
  {
    return Dune::tuple< T2, T3, T4, T5, T6 >( get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ), get< 5 >( t ) );
  }

  template< class T1, class T2, class T3, class T4, class T5, class T6, class T7 >
  inline Dune::tuple< T2, T3, T4, T5, T6, T7 > tuple_pop_front ( const Dune::tuple< T1, T2, T3, T4, T5, T6, T7 > &t )
  {
    return Dune::tuple< T2, T3, T4, T5, T6, T7 >( get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ), get< 5 >( t ), get< 6 >( t ) );
  }

  template< class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8 >
  inline Dune::tuple< T2, T3, T4, T5, T6, T7, T8 > tuple_pop_front ( const Dune::tuple< T1, T2, T3, T4, T5, T6, T7, T8 > &t )
  {
    return Dune::tuple< T2, T3, T4, T5, T6, T7, T8 >( get< 1 >( t ), get< 2 >( t ), get< 3 >( t ), get< 4 >( t ), get< 5 >( t ), get< 6 >( t ), get< 7 >( t ) );
  }

} // namespace Dune

#endif // #ifndef DUNE_COMMON_TUPLES_MODIFIERS_INCLUDE_HH
